export default {
  items: [
    {
      id: 10270250,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
      name: 'react',
      full_name: 'facebook/react',
      private: false,
      owner: {
        login: 'facebook',
        id: 69631,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
        avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/facebook',
        html_url: 'https://github.com/facebook',
        followers_url: 'https://api.github.com/users/facebook/followers',
        following_url: 'https://api.github.com/users/facebook/following{/other_user}',
        gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
        organizations_url: 'https://api.github.com/users/facebook/orgs',
        repos_url: 'https://api.github.com/users/facebook/repos',
        events_url: 'https://api.github.com/users/facebook/events{/privacy}',
        received_events_url: 'https://api.github.com/users/facebook/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/facebook/react',
      description:
        'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
      fork: false,
      url: 'https://api.github.com/repos/facebook/react',
      forks_url: 'https://api.github.com/repos/facebook/react/forks',
      keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/facebook/react/teams',
      hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
      issue_events_url: 'https://api.github.com/repos/facebook/react/issues/events{/number}',
      events_url: 'https://api.github.com/repos/facebook/react/events',
      assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
      branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
      tags_url: 'https://api.github.com/repos/facebook/react/tags',
      blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/facebook/react/languages',
      stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
      contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
      subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
      subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
      commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/facebook/react/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/facebook/react/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
      compare_url: 'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/facebook/react/merges',
      archive_url: 'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
      issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
      pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/facebook/react/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
      releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
      deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
      created_at: '2013-05-24T16:15:54Z',
      updated_at: '2021-02-25T23:29:09Z',
      pushed_at: '2021-02-25T22:25:25Z',
      git_url: 'git://github.com/facebook/react.git',
      ssh_url: 'git@github.com:facebook/react.git',
      clone_url: 'https://github.com/facebook/react.git',
      svn_url: 'https://github.com/facebook/react',
      homepage: 'https://reactjs.org',
      size: 162562,
      stargazers_count: 164237,
      watchers_count: 164237,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 32918,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 709,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 32918,
      open_issues: 709,
      watchers: 164237,
      default_branch: 'master',
      score: 1.0,
    },
    {
      id: 6498492,
      node_id: 'MDEwOlJlcG9zaXRvcnk2NDk4NDky',
      name: 'javascript',
      full_name: 'airbnb/javascript',
      private: false,
      owner: {
        login: 'airbnb',
        id: 698437,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5ODQzNw==',
        avatar_url: 'https://avatars.githubusercontent.com/u/698437?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/airbnb',
        html_url: 'https://github.com/airbnb',
        followers_url: 'https://api.github.com/users/airbnb/followers',
        following_url: 'https://api.github.com/users/airbnb/following{/other_user}',
        gists_url: 'https://api.github.com/users/airbnb/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/airbnb/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/airbnb/subscriptions',
        organizations_url: 'https://api.github.com/users/airbnb/orgs',
        repos_url: 'https://api.github.com/users/airbnb/repos',
        events_url: 'https://api.github.com/users/airbnb/events{/privacy}',
        received_events_url: 'https://api.github.com/users/airbnb/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/airbnb/javascript',
      description: 'JavaScript Style Guide',
      fork: false,
      url: 'https://api.github.com/repos/airbnb/javascript',
      forks_url: 'https://api.github.com/repos/airbnb/javascript/forks',
      keys_url: 'https://api.github.com/repos/airbnb/javascript/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/airbnb/javascript/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/airbnb/javascript/teams',
      hooks_url: 'https://api.github.com/repos/airbnb/javascript/hooks',
      issue_events_url: 'https://api.github.com/repos/airbnb/javascript/issues/events{/number}',
      events_url: 'https://api.github.com/repos/airbnb/javascript/events',
      assignees_url: 'https://api.github.com/repos/airbnb/javascript/assignees{/user}',
      branches_url: 'https://api.github.com/repos/airbnb/javascript/branches{/branch}',
      tags_url: 'https://api.github.com/repos/airbnb/javascript/tags',
      blobs_url: 'https://api.github.com/repos/airbnb/javascript/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/airbnb/javascript/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/airbnb/javascript/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/airbnb/javascript/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/airbnb/javascript/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/airbnb/javascript/languages',
      stargazers_url: 'https://api.github.com/repos/airbnb/javascript/stargazers',
      contributors_url: 'https://api.github.com/repos/airbnb/javascript/contributors',
      subscribers_url: 'https://api.github.com/repos/airbnb/javascript/subscribers',
      subscription_url: 'https://api.github.com/repos/airbnb/javascript/subscription',
      commits_url: 'https://api.github.com/repos/airbnb/javascript/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/airbnb/javascript/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/airbnb/javascript/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/airbnb/javascript/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/airbnb/javascript/contents/{+path}',
      compare_url: 'https://api.github.com/repos/airbnb/javascript/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/airbnb/javascript/merges',
      archive_url: 'https://api.github.com/repos/airbnb/javascript/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/airbnb/javascript/downloads',
      issues_url: 'https://api.github.com/repos/airbnb/javascript/issues{/number}',
      pulls_url: 'https://api.github.com/repos/airbnb/javascript/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/airbnb/javascript/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/airbnb/javascript/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/airbnb/javascript/labels{/name}',
      releases_url: 'https://api.github.com/repos/airbnb/javascript/releases{/id}',
      deployments_url: 'https://api.github.com/repos/airbnb/javascript/deployments',
      created_at: '2012-11-01T23:13:50Z',
      updated_at: '2021-02-26T00:05:39Z',
      pushed_at: '2021-02-25T18:19:32Z',
      git_url: 'git://github.com/airbnb/javascript.git',
      ssh_url: 'git@github.com:airbnb/javascript.git',
      clone_url: 'https://github.com/airbnb/javascript.git',
      svn_url: 'https://github.com/airbnb/javascript',
      homepage: null,
      size: 3283,
      stargazers_count: 105572,
      watchers_count: 105572,
      language: 'JavaScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 20441,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 119,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 20441,
      open_issues: 119,
      watchers: 105572,
      default_branch: 'master',
      score: 1.0,
    },
    {
      id: 29028775,
      node_id: 'MDEwOlJlcG9zaXRvcnkyOTAyODc3NQ==',
      name: 'react-native',
      full_name: 'facebook/react-native',
      private: false,
      owner: {
        login: 'facebook',
        id: 69631,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
        avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/facebook',
        html_url: 'https://github.com/facebook',
        followers_url: 'https://api.github.com/users/facebook/followers',
        following_url: 'https://api.github.com/users/facebook/following{/other_user}',
        gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
        organizations_url: 'https://api.github.com/users/facebook/orgs',
        repos_url: 'https://api.github.com/users/facebook/repos',
        events_url: 'https://api.github.com/users/facebook/events{/privacy}',
        received_events_url: 'https://api.github.com/users/facebook/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/facebook/react-native',
      description: 'A framework for building native apps with React.',
      fork: false,
      url: 'https://api.github.com/repos/facebook/react-native',
      forks_url: 'https://api.github.com/repos/facebook/react-native/forks',
      keys_url: 'https://api.github.com/repos/facebook/react-native/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/facebook/react-native/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/facebook/react-native/teams',
      hooks_url: 'https://api.github.com/repos/facebook/react-native/hooks',
      issue_events_url: 'https://api.github.com/repos/facebook/react-native/issues/events{/number}',
      events_url: 'https://api.github.com/repos/facebook/react-native/events',
      assignees_url: 'https://api.github.com/repos/facebook/react-native/assignees{/user}',
      branches_url: 'https://api.github.com/repos/facebook/react-native/branches{/branch}',
      tags_url: 'https://api.github.com/repos/facebook/react-native/tags',
      blobs_url: 'https://api.github.com/repos/facebook/react-native/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/facebook/react-native/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/facebook/react-native/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/facebook/react-native/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/facebook/react-native/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/facebook/react-native/languages',
      stargazers_url: 'https://api.github.com/repos/facebook/react-native/stargazers',
      contributors_url: 'https://api.github.com/repos/facebook/react-native/contributors',
      subscribers_url: 'https://api.github.com/repos/facebook/react-native/subscribers',
      subscription_url: 'https://api.github.com/repos/facebook/react-native/subscription',
      commits_url: 'https://api.github.com/repos/facebook/react-native/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/facebook/react-native/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/facebook/react-native/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/facebook/react-native/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/facebook/react-native/contents/{+path}',
      compare_url: 'https://api.github.com/repos/facebook/react-native/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/facebook/react-native/merges',
      archive_url: 'https://api.github.com/repos/facebook/react-native/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/facebook/react-native/downloads',
      issues_url: 'https://api.github.com/repos/facebook/react-native/issues{/number}',
      pulls_url: 'https://api.github.com/repos/facebook/react-native/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/facebook/react-native/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/facebook/react-native/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/facebook/react-native/labels{/name}',
      releases_url: 'https://api.github.com/repos/facebook/react-native/releases{/id}',
      deployments_url: 'https://api.github.com/repos/facebook/react-native/deployments',
      created_at: '2015-01-09T18:10:16Z',
      updated_at: '2021-02-25T23:38:37Z',
      pushed_at: '2021-02-25T23:28:50Z',
      git_url: 'git://github.com/facebook/react-native.git',
      ssh_url: 'git@github.com:facebook/react-native.git',
      clone_url: 'https://github.com/facebook/react-native.git',
      svn_url: 'https://github.com/facebook/react-native',
      homepage: 'https://reactnative.dev',
      size: 700886,
      stargazers_count: 93559,
      watchers_count: 93559,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 20541,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 1478,
      license: {
        key: 'other',
        name: 'Other',
        spdx_id: 'NOASSERTION',
        url: null,
        node_id: 'MDc6TGljZW5zZTA=',
      },
      forks: 20541,
      open_issues: 1478,
      watchers: 93559,
      default_branch: 'master',
      score: 1.0,
    },
  ],
};
