export const mockList = {
  total_count: 9958218,
  incomplete_results: true,
  items: [
    {
      id: 11730342,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMTczMDM0Mg==',
      name: 'vue',
      full_name: 'vuejs/vue',
      private: false,
      owner: {
        login: 'vuejs',
        id: 6128107,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjYxMjgxMDc=',
        avatar_url: 'https://avatars.githubusercontent.com/u/6128107?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/vuejs',
        html_url: 'https://github.com/vuejs',
        followers_url: 'https://api.github.com/users/vuejs/followers',
        following_url: 'https://api.github.com/users/vuejs/following{/other_user}',
        gists_url: 'https://api.github.com/users/vuejs/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/vuejs/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/vuejs/subscriptions',
        organizations_url: 'https://api.github.com/users/vuejs/orgs',
        repos_url: 'https://api.github.com/users/vuejs/repos',
        events_url: 'https://api.github.com/users/vuejs/events{/privacy}',
        received_events_url: 'https://api.github.com/users/vuejs/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/vuejs/vue',
      description:
        '🖖 Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.',
      fork: false,
      url: 'https://api.github.com/repos/vuejs/vue',
      forks_url: 'https://api.github.com/repos/vuejs/vue/forks',
      keys_url: 'https://api.github.com/repos/vuejs/vue/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/vuejs/vue/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/vuejs/vue/teams',
      hooks_url: 'https://api.github.com/repos/vuejs/vue/hooks',
      issue_events_url: 'https://api.github.com/repos/vuejs/vue/issues/events{/number}',
      events_url: 'https://api.github.com/repos/vuejs/vue/events',
      assignees_url: 'https://api.github.com/repos/vuejs/vue/assignees{/user}',
      branches_url: 'https://api.github.com/repos/vuejs/vue/branches{/branch}',
      tags_url: 'https://api.github.com/repos/vuejs/vue/tags',
      blobs_url: 'https://api.github.com/repos/vuejs/vue/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/vuejs/vue/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/vuejs/vue/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/vuejs/vue/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/vuejs/vue/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/vuejs/vue/languages',
      stargazers_url: 'https://api.github.com/repos/vuejs/vue/stargazers',
      contributors_url: 'https://api.github.com/repos/vuejs/vue/contributors',
      subscribers_url: 'https://api.github.com/repos/vuejs/vue/subscribers',
      subscription_url: 'https://api.github.com/repos/vuejs/vue/subscription',
      commits_url: 'https://api.github.com/repos/vuejs/vue/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/vuejs/vue/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/vuejs/vue/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/vuejs/vue/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/vuejs/vue/contents/{+path}',
      compare_url: 'https://api.github.com/repos/vuejs/vue/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/vuejs/vue/merges',
      archive_url: 'https://api.github.com/repos/vuejs/vue/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/vuejs/vue/downloads',
      issues_url: 'https://api.github.com/repos/vuejs/vue/issues{/number}',
      pulls_url: 'https://api.github.com/repos/vuejs/vue/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/vuejs/vue/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/vuejs/vue/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/vuejs/vue/labels{/name}',
      releases_url: 'https://api.github.com/repos/vuejs/vue/releases{/id}',
      deployments_url: 'https://api.github.com/repos/vuejs/vue/deployments',
      created_at: '2013-07-29T03:24:51Z',
      updated_at: '2021-03-07T17:24:55Z',
      pushed_at: '2021-03-07T16:52:20Z',
      git_url: 'git://github.com/vuejs/vue.git',
      ssh_url: 'git@github.com:vuejs/vue.git',
      clone_url: 'https://github.com/vuejs/vue.git',
      svn_url: 'https://github.com/vuejs/vue',
      homepage: 'http://vuejs.org',
      size: 27444,
      stargazers_count: 180293,
      watchers_count: 180293,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 28352,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 567,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 28352,
      open_issues: 567,
      watchers: 180293,
      default_branch: 'dev',
      score: 1.0,
    },
    {
      id: 10270250,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
      name: 'react',
      full_name: 'facebook/react',
      private: false,
      owner: {
        login: 'facebook',
        id: 69631,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
        avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/facebook',
        html_url: 'https://github.com/facebook',
        followers_url: 'https://api.github.com/users/facebook/followers',
        following_url: 'https://api.github.com/users/facebook/following{/other_user}',
        gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
        organizations_url: 'https://api.github.com/users/facebook/orgs',
        repos_url: 'https://api.github.com/users/facebook/repos',
        events_url: 'https://api.github.com/users/facebook/events{/privacy}',
        received_events_url: 'https://api.github.com/users/facebook/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/facebook/react',
      description:
        'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
      fork: false,
      url: 'https://api.github.com/repos/facebook/react',
      forks_url: 'https://api.github.com/repos/facebook/react/forks',
      keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/facebook/react/teams',
      hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
      issue_events_url: 'https://api.github.com/repos/facebook/react/issues/events{/number}',
      events_url: 'https://api.github.com/repos/facebook/react/events',
      assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
      branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
      tags_url: 'https://api.github.com/repos/facebook/react/tags',
      blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/facebook/react/languages',
      stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
      contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
      subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
      subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
      commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/facebook/react/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/facebook/react/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
      compare_url: 'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/facebook/react/merges',
      archive_url: 'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
      issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
      pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/facebook/react/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
      releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
      deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
      created_at: '2013-05-24T16:15:54Z',
      updated_at: '2021-03-07T17:24:47Z',
      pushed_at: '2021-03-07T17:20:01Z',
      git_url: 'git://github.com/facebook/react.git',
      ssh_url: 'git@github.com:facebook/react.git',
      clone_url: 'https://github.com/facebook/react.git',
      svn_url: 'https://github.com/facebook/react',
      homepage: 'https://reactjs.org',
      size: 162659,
      stargazers_count: 164736,
      watchers_count: 164736,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 33060,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 731,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 33060,
      open_issues: 731,
      watchers: 164736,
      default_branch: 'master',
      score: 1.0,
    },
    {
      id: 2126244,
      node_id: 'MDEwOlJlcG9zaXRvcnkyMTI2MjQ0',
      name: 'bootstrap',
      full_name: 'twbs/bootstrap',
      private: false,
      owner: {
        login: 'twbs',
        id: 2918581,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjI5MTg1ODE=',
        avatar_url: 'https://avatars.githubusercontent.com/u/2918581?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/twbs',
        html_url: 'https://github.com/twbs',
        followers_url: 'https://api.github.com/users/twbs/followers',
        following_url: 'https://api.github.com/users/twbs/following{/other_user}',
        gists_url: 'https://api.github.com/users/twbs/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/twbs/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/twbs/subscriptions',
        organizations_url: 'https://api.github.com/users/twbs/orgs',
        repos_url: 'https://api.github.com/users/twbs/repos',
        events_url: 'https://api.github.com/users/twbs/events{/privacy}',
        received_events_url: 'https://api.github.com/users/twbs/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/twbs/bootstrap',
      description:
        'The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.',
      fork: false,
      url: 'https://api.github.com/repos/twbs/bootstrap',
      forks_url: 'https://api.github.com/repos/twbs/bootstrap/forks',
      keys_url: 'https://api.github.com/repos/twbs/bootstrap/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/twbs/bootstrap/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/twbs/bootstrap/teams',
      hooks_url: 'https://api.github.com/repos/twbs/bootstrap/hooks',
      issue_events_url: 'https://api.github.com/repos/twbs/bootstrap/issues/events{/number}',
      events_url: 'https://api.github.com/repos/twbs/bootstrap/events',
      assignees_url: 'https://api.github.com/repos/twbs/bootstrap/assignees{/user}',
      branches_url: 'https://api.github.com/repos/twbs/bootstrap/branches{/branch}',
      tags_url: 'https://api.github.com/repos/twbs/bootstrap/tags',
      blobs_url: 'https://api.github.com/repos/twbs/bootstrap/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/twbs/bootstrap/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/twbs/bootstrap/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/twbs/bootstrap/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/twbs/bootstrap/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/twbs/bootstrap/languages',
      stargazers_url: 'https://api.github.com/repos/twbs/bootstrap/stargazers',
      contributors_url: 'https://api.github.com/repos/twbs/bootstrap/contributors',
      subscribers_url: 'https://api.github.com/repos/twbs/bootstrap/subscribers',
      subscription_url: 'https://api.github.com/repos/twbs/bootstrap/subscription',
      commits_url: 'https://api.github.com/repos/twbs/bootstrap/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/twbs/bootstrap/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/twbs/bootstrap/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/twbs/bootstrap/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/twbs/bootstrap/contents/{+path}',
      compare_url: 'https://api.github.com/repos/twbs/bootstrap/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/twbs/bootstrap/merges',
      archive_url: 'https://api.github.com/repos/twbs/bootstrap/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/twbs/bootstrap/downloads',
      issues_url: 'https://api.github.com/repos/twbs/bootstrap/issues{/number}',
      pulls_url: 'https://api.github.com/repos/twbs/bootstrap/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/twbs/bootstrap/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/twbs/bootstrap/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/twbs/bootstrap/labels{/name}',
      releases_url: 'https://api.github.com/repos/twbs/bootstrap/releases{/id}',
      deployments_url: 'https://api.github.com/repos/twbs/bootstrap/deployments',
      created_at: '2011-07-29T21:19:00Z',
      updated_at: '2021-03-07T16:03:53Z',
      pushed_at: '2021-03-07T15:10:13Z',
      git_url: 'git://github.com/twbs/bootstrap.git',
      ssh_url: 'git@github.com:twbs/bootstrap.git',
      clone_url: 'https://github.com/twbs/bootstrap.git',
      svn_url: 'https://github.com/twbs/bootstrap',
      homepage: 'https://getbootstrap.com',
      size: 176569,
      stargazers_count: 148642,
      watchers_count: 148642,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: true,
      forks_count: 72505,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 356,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 72505,
      open_issues: 356,
      watchers: 148642,
      default_branch: 'main',
      score: 1.0,
    },
    {
      id: 6498492,
      node_id: 'MDEwOlJlcG9zaXRvcnk2NDk4NDky',
      name: 'javascript',
      full_name: 'airbnb/javascript',
      private: false,
      owner: {
        login: 'airbnb',
        id: 698437,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5ODQzNw==',
        avatar_url: 'https://avatars.githubusercontent.com/u/698437?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/airbnb',
        html_url: 'https://github.com/airbnb',
        followers_url: 'https://api.github.com/users/airbnb/followers',
        following_url: 'https://api.github.com/users/airbnb/following{/other_user}',
        gists_url: 'https://api.github.com/users/airbnb/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/airbnb/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/airbnb/subscriptions',
        organizations_url: 'https://api.github.com/users/airbnb/orgs',
        repos_url: 'https://api.github.com/users/airbnb/repos',
        events_url: 'https://api.github.com/users/airbnb/events{/privacy}',
        received_events_url: 'https://api.github.com/users/airbnb/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/airbnb/javascript',
      description: 'JavaScript Style Guide',
      fork: false,
      url: 'https://api.github.com/repos/airbnb/javascript',
      forks_url: 'https://api.github.com/repos/airbnb/javascript/forks',
      keys_url: 'https://api.github.com/repos/airbnb/javascript/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/airbnb/javascript/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/airbnb/javascript/teams',
      hooks_url: 'https://api.github.com/repos/airbnb/javascript/hooks',
      issue_events_url: 'https://api.github.com/repos/airbnb/javascript/issues/events{/number}',
      events_url: 'https://api.github.com/repos/airbnb/javascript/events',
      assignees_url: 'https://api.github.com/repos/airbnb/javascript/assignees{/user}',
      branches_url: 'https://api.github.com/repos/airbnb/javascript/branches{/branch}',
      tags_url: 'https://api.github.com/repos/airbnb/javascript/tags',
      blobs_url: 'https://api.github.com/repos/airbnb/javascript/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/airbnb/javascript/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/airbnb/javascript/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/airbnb/javascript/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/airbnb/javascript/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/airbnb/javascript/languages',
      stargazers_url: 'https://api.github.com/repos/airbnb/javascript/stargazers',
      contributors_url: 'https://api.github.com/repos/airbnb/javascript/contributors',
      subscribers_url: 'https://api.github.com/repos/airbnb/javascript/subscribers',
      subscription_url: 'https://api.github.com/repos/airbnb/javascript/subscription',
      commits_url: 'https://api.github.com/repos/airbnb/javascript/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/airbnb/javascript/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/airbnb/javascript/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/airbnb/javascript/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/airbnb/javascript/contents/{+path}',
      compare_url: 'https://api.github.com/repos/airbnb/javascript/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/airbnb/javascript/merges',
      archive_url: 'https://api.github.com/repos/airbnb/javascript/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/airbnb/javascript/downloads',
      issues_url: 'https://api.github.com/repos/airbnb/javascript/issues{/number}',
      pulls_url: 'https://api.github.com/repos/airbnb/javascript/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/airbnb/javascript/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/airbnb/javascript/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/airbnb/javascript/labels{/name}',
      releases_url: 'https://api.github.com/repos/airbnb/javascript/releases{/id}',
      deployments_url: 'https://api.github.com/repos/airbnb/javascript/deployments',
      created_at: '2012-11-01T23:13:50Z',
      updated_at: '2021-03-07T16:38:44Z',
      pushed_at: '2021-03-04T17:25:10Z',
      git_url: 'git://github.com/airbnb/javascript.git',
      ssh_url: 'git@github.com:airbnb/javascript.git',
      clone_url: 'https://github.com/airbnb/javascript.git',
      svn_url: 'https://github.com/airbnb/javascript',
      homepage: null,
      size: 3283,
      stargazers_count: 106191,
      watchers_count: 106191,
      language: 'JavaScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 20529,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 120,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 20529,
      open_issues: 120,
      watchers: 106191,
      default_branch: 'master',
      score: 1.0,
    },
    {
      id: 123458551,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMjM0NTg1NTE=',
      name: 'Python-100-Days',
      full_name: 'jackfrued/Python-100-Days',
      private: false,
      owner: {
        login: 'jackfrued',
        id: 7474657,
        node_id: 'MDQ6VXNlcjc0NzQ2NTc=',
        avatar_url: 'https://avatars.githubusercontent.com/u/7474657?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/jackfrued',
        html_url: 'https://github.com/jackfrued',
        followers_url: 'https://api.github.com/users/jackfrued/followers',
        following_url: 'https://api.github.com/users/jackfrued/following{/other_user}',
        gists_url: 'https://api.github.com/users/jackfrued/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/jackfrued/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/jackfrued/subscriptions',
        organizations_url: 'https://api.github.com/users/jackfrued/orgs',
        repos_url: 'https://api.github.com/users/jackfrued/repos',
        events_url: 'https://api.github.com/users/jackfrued/events{/privacy}',
        received_events_url: 'https://api.github.com/users/jackfrued/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/jackfrued/Python-100-Days',
      description: 'Python - 100天从新手到大师',
      fork: false,
      url: 'https://api.github.com/repos/jackfrued/Python-100-Days',
      forks_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/forks',
      keys_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/jackfrued/Python-100-Days/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/teams',
      hooks_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/hooks',
      issue_events_url:
        'https://api.github.com/repos/jackfrued/Python-100-Days/issues/events{/number}',
      events_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/events',
      assignees_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/assignees{/user}',
      branches_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/branches{/branch}',
      tags_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/tags',
      blobs_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/languages',
      stargazers_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/stargazers',
      contributors_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/contributors',
      subscribers_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/subscribers',
      subscription_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/subscription',
      commits_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/jackfrued/Python-100-Days/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/contents/{+path}',
      compare_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/merges',
      archive_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/downloads',
      issues_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/issues{/number}',
      pulls_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/jackfrued/Python-100-Days/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/labels{/name}',
      releases_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/releases{/id}',
      deployments_url: 'https://api.github.com/repos/jackfrued/Python-100-Days/deployments',
      created_at: '2018-03-01T16:05:52Z',
      updated_at: '2021-03-07T16:26:29Z',
      pushed_at: '2021-03-07T16:25:29Z',
      git_url: 'git://github.com/jackfrued/Python-100-Days.git',
      ssh_url: 'git@github.com:jackfrued/Python-100-Days.git',
      clone_url: 'https://github.com/jackfrued/Python-100-Days.git',
      svn_url: 'https://github.com/jackfrued/Python-100-Days',
      homepage: '',
      size: 302246,
      stargazers_count: 100314,
      watchers_count: 100314,
      language: 'Python',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 40268,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 542,
      license: null,
      forks: 40268,
      open_issues: 542,
      watchers: 100314,
      default_branch: 'master',
      score: 1.0,
    },
  ],
};
